registry:
  url: http://localhost:8081
  addoperationid: add
  searchoperationid: search
  readoperationid: read
keycloak:
  url: https://divoc.xiv.in/keycloak/auth
  authheader: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1aUd3ZF93WUNxLUo0QTMxUnEySG15bExTUXBUb19zOEFBcEg1bGl1dF9vIn0.eyJleHAiOjE2MjYzNzg2MTYsImlhdCI6MTYwOTA5ODYxNiwianRpIjoiMzY5NTcxZjktODZkYS00YjA0LThmOWYtMTY5YjU5Yjg4M2M2IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdC9hdXRoL3JlYWxtcy9kaXZvYyIsImF1ZCI6WyJyZWFsbS1tYW5hZ2VtZW50IiwiYWNjb3VudCJdLCJzdWIiOiJkOWU2OGJlNC0yMDVhLTRiNDQtODMwMS0xZmVhMjU1N2YxY2YiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhZG1pbi1hcGkiLCJzZXNzaW9uX3N0YXRlIjoiZjIwYmFiZTItMmVlMC00ZTI1LWJkZDgtN2MzYTJjYTQxZjhlIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL2Rpdm9jLnhpdi5pbiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InJlYWxtLW1hbmFnZW1lbnQiOnsicm9sZXMiOlsibWFuYWdlLXVzZXJzIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJjbGllbnRJZCI6ImFkbWluLWFwaSIsImNsaWVudEhvc3QiOiIxNzIuMjIuMC4xMyIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoic2VydmljZS1hY2NvdW50LWFkbWluLWFwaSIsImNsaWVudEFkZHJlc3MiOiIxNzIuMjIuMC4xMyJ9.klKE2OIyeDGs5c5YyX5vaui92TDR726_XYp9YIw2M1F0beScG0W8VHnLCMC_ru_MAjm7fibqLgu6TRof7iKfpMhUTSoWPMLav2wVGdntWbzA2uleGkSl5Nh3BadtsXr_tWigrNDFMRDJ4MMRhJBCos5HmxRLSAiONuzqmvYEwRH4m5Kww2GJ28Vomv6IcOo862b9QLZpOMglJ5c5z4Zy3hYbt4ui-P1K2XM7yVob7kc4K5Pd3eeBpRqfEdpEiZd0YyxDE4LN7WLVfWuS3ROFDCTOOmMuFlDxKYS07CG6ATHw-KiWTolTCwyBtqR3sB922u-1w8a2MIGmO1zKpwlIwQ
  recipientgroupid: 7a859744-fae3-4d24-9f1c-4aeed92ba383
kafka:
  bootstrapServers: localhost
  certifyTopic: certify
  eventsTopic: events
clickhouse:
  dsn: tcp://127.0.0.1:9000?debug=true