version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  registry:
    image: dockerhub/open-saber
    environment:
      - connectionInfo_uri=jdbc:postgresql://db:5432/postgres
      - connectionInfo_username=postgres
      - connectionInfo_password=postgres
    #command: java -Xms1024m -Xmx2048m -XX:+UseG1GC -Dserver.port=8081 -jar /home/opensaber/registry.jar
    volumes:
      - .:/home/opensaber/config/public/_schemas
    ports:
      - "8081:8081"
    depends_on:
      - db