apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  labels:
    k8s-app: caching-dash-server
  name: caching-dash-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: caching-dash-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: caching-dash-server
      name: caching-dash-server
    spec:
      containers:
        - image: dockerhub/caching-dash-server
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: divoc-config
          name: caching-dash-server
          resources:
            requests:
              cpu: 60m
            limits:
              cpu: 200m
          livenessProbe:
            tcpSocket:
              port: 8004
            initialDelaySeconds: 2
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30