apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    k8s-app: caching-dash-server
  name: caching-dash-server
spec:
  ports:
    - name: "tcp-8004"
      port: 8004
      protocol: TCP
      targetPort: 8004
  selector:
    k8s-app: caching-dash-server
  sessionAffinity: None