kafka:
  bootstrapservers: localhost:9092
  notifyTopic: notify
  enrollmenttopic: enrollment
enrollmentcreation:
  maxretrycount: 10
  lengthofsuffixedenrollmentcode: 3
auth:
  privatekeypath: config/key.pem
  publickeypath: config/pubkey.pem
  maxotpverifyattempts: 3
  ttlforotpinminutes: 5
