kafka:
  bootstrapservers: localhost:9092
  notifyTopic: notify
  enrollmenttopic: enrollment
  recipientappointmenttopic: recipientappointment
enrollmentcreation:
  maxretrycount: 10
  lengthofsuffixedenrollmentcode: 3
auth:
  maxotpverifyattempts: 3
  ttlforotpinminutes: 5
