swagger: '2.0'
info:
  version: '1.0.0'
  title: Notification service to integrate with DIVOC
#https://app.swaggerhub.com/apis/divoc/notification-servic/1.0.0
# Under securityDefinitions we declare which security schemes can be used.
# These definitions do not affect to the operations, but can be applied
# using the 'security' key at the global level or the operation level.
# In this sample, we'll see how to apply the security definition globally,
# and override it at the operation level.
#
# Note that for Access Code Flow, you must provide the Token URL.
securityDefinitions: #TODO check security for provider
  accessCode:
    type: oauth2
    # This should be updated to the Token URL of your OAuth provider.
    tokenUrl: http://example.com/oauth/token
    # This should be updated to the Authorization URL of your OAuth provider.
    authorizationUrl: http://example.com/oauth/auth
    flow: accessCode
    scopes:
      write: allows modifying resources
      read: allows reading resources

# Here we apply the security flow called 'accessCode' globally to all the operations in the spec.
# This security scheme is defined above in the 'securityDefinitions' section.
# Global security can be overridden an operation level as seen in the example below
security:
  - accessCode:
      - read
      - write
paths:
  /notification:
    post:
      tags:
        - notification
      summary: Notify the intended person using different channels
      description: Common notification service for different channels like eSMS, email etc. Target address can depict specifics about mode and channel
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/NotificationRequest'
      responses:
        200:
          description: OK
definitions:
  NotificationRequest:
    type: object
    required:
      - recepient
      - message
    properties:
      recepient:
        type: string
        description: this can use address like tel:234343434 or mailto:user@example.com
      message:
        type: string
      subject:
        type: string
      #attachment:
      #  type:

host: virtserver.swaggerhub.com
basePath: /divoc/notification-servic/1.0.0
schemes:
  - https