swagger: "2.0"
info:
  title: Registration API
  description: Registration API
  version: 1.0.0
schemes:
  - https
basePath: /divoc/api/citizen
consumes:
  - application/json
produces:
  - application/json
paths:
  /register:
    post:
      summary: Enroll Recipient
      operationId: enrollRecipient
      parameters:
        - in: body
          name: body
          schema:
            $ref: '../registry/Enrollment.json#/definitions/Enrollment'
          description: Recipient Details
      responses:
        '200':
          description: OK
  /generateOTP:
   post:
     summary: Generate OTP
     operationId: generateOTP
     parameters:
       - in: body
         name: body
         required: true
         schema:
          type: object
          properties:
            phone:
              type: string
     responses:
       '200':
         description: OK
       '204':
         description: Phone number is empty
       '500':
         description: Intern Error
  /verifyOTP:
    post:
      summary: Verify OTP
      operationId: verifyOTP
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              phone:
                type: string
              otp:
                type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              token:
                type: string
        '401':
          description: Invalid OTP
        '204':
          description: OTP is empty